version: '1'
services:
  postgres-unicorn:
    image: postgres:13
    environment:
      POSTGRES_USER: realestate
      POSTGRES_PASSWORD: realestate
      POSTGRES_DB: realestate
    restart: always
    ports: 
        - 5432:5432
  web-scraper-scripts: 
    build: 
      context: .
      dockerfile: Docker/Dockerfile
    volumes:
      - ./web-scraper:/home/web-scraper

